/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Usuario
 */
public class ClienteF extends javax.swing.JFrame {
    private Cliente cliente;
    private JLabel[][] tablero =new JLabel[7][6];
    private JButton[] botones = new JButton[7];

    private int columna=0;
    private int fila=0;
    /**
     * Creates new form ClienteF
     */
    public ClienteF() {
        initComponents();
        tablero[0][0]=jLabel0_0;
        tablero[0][1]=jLabel0_1;
        tablero[0][2]=jLabel0_2;
        tablero[0][3]=jLabel0_3;
        tablero[0][4]=jLabel0_4;
        tablero[0][5]=jLabel0_5;
        tablero[1][0]=jLabel1_0;
        tablero[1][1]=jLabel1_1;
        tablero[1][2]=jLabel1_2;
        tablero[1][3]=jLabel1_3;
        tablero[1][4]=jLabel1_4;
        tablero[1][5]=jLabel1_5;
        tablero[2][0]=jLabel2_0;
        tablero[2][1]=jLabel2_1;
        tablero[2][2]=jLabel2_2;
        tablero[2][3]=jLabel2_3;
        tablero[2][4]=jLabel2_4;
        tablero[2][5]=jLabel2_5;
        tablero[3][0]=jLabel3_0;
        tablero[3][1]=jLabel3_1;
        tablero[3][2]=jLabel3_2;
        tablero[3][3]=jLabel3_3;
        tablero[3][4]=jLabel3_4;
        tablero[3][5]=jLabel3_5;
        tablero[4][0]=jLabel4_0;
        tablero[4][1]=jLabel4_1;
        tablero[4][2]=jLabel4_2;
        tablero[4][3]=jLabel4_3;
        tablero[4][4]=jLabel4_4;
        tablero[4][5]=jLabel4_5;
        tablero[5][0]=jLabel5_0;
        tablero[5][1]=jLabel5_1;
        tablero[5][2]=jLabel5_2;
        tablero[5][3]=jLabel5_3;
        tablero[5][4]=jLabel5_4;
        tablero[5][5]=jLabel5_5;
        tablero[6][0]=jLabel6_0;
        tablero[6][1]=jLabel6_1;
        tablero[6][2]=jLabel6_2;
        tablero[6][3]=jLabel6_3;
        tablero[6][4]=jLabel6_4;
        tablero[6][5]=jLabel6_5;
        botones[0]=jButton1;
        botones[1]=jButton2;
        botones[2]=jButton3;
        botones[3]=jButton4;
        botones[4]=jButton5;
        botones[5]=jButton6;
        botones[6]=jButton7;

        cliente = new Cliente(this);
        Thread t = new Thread(cliente);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel0_5 = new javax.swing.JLabel();
        jLabel0_4 = new javax.swing.JLabel();
        jLabel0_3 = new javax.swing.JLabel();
        jLabel0_2 = new javax.swing.JLabel();
        jLabel0_1 = new javax.swing.JLabel();
        jLabel0_0 = new javax.swing.JLabel();
        jLabel1_5 = new javax.swing.JLabel();
        jLabel1_4 = new javax.swing.JLabel();
        jLabel1_3 = new javax.swing.JLabel();
        jLabel1_2 = new javax.swing.JLabel();
        jLabel1_1 = new javax.swing.JLabel();
        jLabel1_0 = new javax.swing.JLabel();
        jLabel3_5 = new javax.swing.JLabel();
        jLabel2_5 = new javax.swing.JLabel();
        jLabel2_4 = new javax.swing.JLabel();
        jLabel3_4 = new javax.swing.JLabel();
        jLabel3_3 = new javax.swing.JLabel();
        jLabel2_3 = new javax.swing.JLabel();
        jLabel2_2 = new javax.swing.JLabel();
        jLabel3_2 = new javax.swing.JLabel();
        jLabel3_1 = new javax.swing.JLabel();
        jLabel2_1 = new javax.swing.JLabel();
        jLabel2_0 = new javax.swing.JLabel();
        jLabel3_0 = new javax.swing.JLabel();
        jLabel4_5 = new javax.swing.JLabel();
        jLabel4_4 = new javax.swing.JLabel();
        jLabel4_3 = new javax.swing.JLabel();
        jLabel4_2 = new javax.swing.JLabel();
        jLabel4_1 = new javax.swing.JLabel();
        jLabel4_0 = new javax.swing.JLabel();
        jLabel5_5 = new javax.swing.JLabel();
        jLabel5_4 = new javax.swing.JLabel();
        jLabel5_3 = new javax.swing.JLabel();
        jLabel5_2 = new javax.swing.JLabel();
        jLabel5_1 = new javax.swing.JLabel();
        jLabel5_0 = new javax.swing.JLabel();
        jLabel6_5 = new javax.swing.JLabel();
        jLabel6_4 = new javax.swing.JLabel();
        jLabel6_3 = new javax.swing.JLabel();
        jLabel6_2 = new javax.swing.JLabel();
        jLabel6_1 = new javax.swing.JLabel();
        jLabel6_0 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 162, 232));

        jLabel0_5.setBackground(Color.white);
        jLabel0_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel0_4.setBackground(Color.white);
        jLabel0_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel0_3.setBackground(Color.white);
        jLabel0_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel0_2.setBackground(Color.white);
        jLabel0_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel0_1.setBackground(Color.white);
        jLabel0_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel0_0.setBackground(Color.white);
        jLabel0_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_5.setBackground(Color.white);
        jLabel1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_4.setBackground(Color.white);
        jLabel1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_3.setBackground(Color.white);
        jLabel1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_2.setBackground(Color.white);
        jLabel1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_1.setBackground(Color.white);
        jLabel1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel1_0.setBackground(Color.white);
        jLabel1_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_5.setBackground(Color.white);
        jLabel3_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_5.setBackground(Color.white);
        jLabel2_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_4.setBackground(Color.white);
        jLabel2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_4.setBackground(Color.white);
        jLabel3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_3.setBackground(Color.white);
        jLabel3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_3.setBackground(Color.white);
        jLabel2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_2.setBackground(Color.white);
        jLabel2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_2.setBackground(Color.white);
        jLabel3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_1.setBackground(Color.white);
        jLabel3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_1.setBackground(Color.white);
        jLabel2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel2_0.setBackground(Color.white);
        jLabel2_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel3_0.setBackground(Color.white);
        jLabel3_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_5.setBackground(Color.white);
        jLabel4_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_4.setBackground(Color.white);
        jLabel4_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_3.setBackground(Color.white);
        jLabel4_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_2.setBackground(Color.white);
        jLabel4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_1.setBackground(Color.white);
        jLabel4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel4_0.setBackground(Color.white);
        jLabel4_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_5.setBackground(Color.white);
        jLabel5_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_4.setBackground(Color.white);
        jLabel5_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_3.setBackground(Color.white);
        jLabel5_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_2.setBackground(Color.white);
        jLabel5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_1.setBackground(Color.white);
        jLabel5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel5_0.setBackground(Color.white);
        jLabel5_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_5.setBackground(Color.white);
        jLabel6_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_4.setBackground(Color.white);
        jLabel6_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_3.setBackground(Color.white);
        jLabel6_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_2.setBackground(Color.white);
        jLabel6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_1.setBackground(Color.white);
        jLabel6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel6_0.setBackground(Color.white);
        jLabel6_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blancas.png"))); // NOI18N

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setOpaque(true);
        //listener botones
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel0_5)
                    .addComponent(jLabel0_4)
                    .addComponent(jLabel0_3)
                    .addComponent(jLabel0_2)
                    .addComponent(jLabel0_1)
                    .addComponent(jLabel0_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_5)
                    .addComponent(jLabel1_4)
                    .addComponent(jLabel1_3)
                    .addComponent(jLabel1_2)
                    .addComponent(jLabel1_1)
                    .addComponent(jLabel1_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2_5)
                    .addComponent(jLabel2_4)
                    .addComponent(jLabel2_3)
                    .addComponent(jLabel2_2)
                    .addComponent(jLabel2_1)
                    .addComponent(jLabel2_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5_0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6_0)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton2.setSelected(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton3.setSelected(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton4.setSelected(true);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton5.setSelected(true);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton6.setSelected(true);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton7.setSelected(true);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setText("JUEGAS:");

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png"))); // NOI18N
        jButton1.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(ActionEvent evt) {
        if (jLabel6_0.getBackground() !=Color.white && jLabel6_1.getBackground() != Color.white && jLabel6_2.getBackground() != Color.white && jLabel6_3.getBackground() != Color.white && jLabel6_4.getBackground() != Color.white && jLabel6_5.getBackground()!= Color.white){
            jButton7.setEnabled(false);
        }
        if (jLabel6_0.getBackground() != Color.white && jLabel6_1.getBackground() != Color.white && jLabel6_2.getBackground() != Color.white && jLabel6_3.getBackground() != Color.white && jLabel6_4.getBackground() != Color.white && jLabel6_5.getBackground() == Color.white) {
            fila = 5;
            columna = 6;
            enviarTurno(columna, fila);
        }
        else if (jLabel6_0.getBackground() != Color.white && jLabel6_1.getBackground() != Color.white && jLabel6_2.getBackground() != Color.white && jLabel6_3.getBackground() != Color.white && jLabel6_4.getBackground()  == Color.white ) {
            fila = 4;
            columna = 6;
            enviarTurno(columna, fila);
        }
        else if (jLabel6_0.getBackground() != Color.white && jLabel6_1.getBackground() != Color.white && jLabel6_2.getBackground() != Color.white && jLabel6_3.getBackground() == Color.white) {
            fila = 3;
            columna = 6;
            enviarTurno(columna, fila);
        }
        else if (jLabel6_0.getBackground() != Color.white && jLabel6_1.getBackground() != Color.white && jLabel6_2.getBackground() == Color.white) {
            fila = 2;
            columna = 6;
            enviarTurno(columna, fila);
        }
        else if (jLabel6_0.getBackground() != Color.white && jLabel6_1.getBackground() == Color.white) {
            fila = 1;
            columna = 6;
            enviarTurno(columna, fila);

        }
        else if (jLabel6_0.getBackground() == Color.white) {
            fila = 0;
            columna = 6;
            enviarTurno(columna, fila);
        }
    }

    private void jButton6ActionPerformed(ActionEvent evt) {
        if (jLabel5_0.getBackground() !=Color.white && jLabel3_1.getBackground() != Color.white && jLabel5_2.getBackground() != Color.white && jLabel5_3.getBackground() != Color.white && jLabel5_4.getBackground() != Color.white && jLabel5_5.getBackground()!= Color.white){
            jButton6.setEnabled(false);
        }
        if (jLabel5_0.getBackground() != Color.white && jLabel5_1.getBackground() != Color.white && jLabel5_2.getBackground() != Color.white && jLabel5_3.getBackground() != Color.white && jLabel5_4.getBackground() != Color.white && jLabel5_5.getBackground() == Color.white) {
            fila = 5;
            columna = 5;
            enviarTurno(columna, fila);
        }
        else if (jLabel5_0.getBackground() != Color.white && jLabel5_1.getBackground() != Color.white && jLabel5_2.getBackground() != Color.white && jLabel5_3.getBackground() != Color.white && jLabel5_4.getBackground()  == Color.white ) {
            fila = 4;
            columna = 5;
            enviarTurno(columna, fila);
        }
        else if (jLabel5_0.getBackground() != Color.white && jLabel5_1.getBackground() != Color.white && jLabel5_2.getBackground() != Color.white && jLabel5_3.getBackground() == Color.white) {
            fila = 3;
            columna = 5;
            enviarTurno(columna, fila);
        }
        else if (jLabel5_0.getBackground() != Color.white && jLabel5_1.getBackground() != Color.white && jLabel5_2.getBackground() == Color.white) {
            fila = 2;
            columna = 5;
            enviarTurno(columna, fila);
        }
        else if (jLabel5_0.getBackground() != Color.white && jLabel5_1.getBackground() == Color.white) {
            fila = 1;
            columna = 5;
            enviarTurno(columna, fila);

        }
        else if (jLabel5_0.getBackground() == Color.white) {
            fila = 0;
            columna = 5;
            enviarTurno(columna, fila);
        }
    }

    private void jButton5ActionPerformed(ActionEvent evt) {
        if (jLabel4_0.getBackground() !=Color.white && jLabel4_1.getBackground() != Color.white && jLabel4_2.getBackground() != Color.white && jLabel4_3.getBackground() != Color.white && jLabel4_4.getBackground() != Color.white && jLabel4_5.getBackground()!= Color.white){
            jButton5.setEnabled(false);
        }
        if (jLabel4_0.getBackground() != Color.white && jLabel3_1.getBackground() != Color.white && jLabel4_2.getBackground() != Color.white && jLabel4_3.getBackground() != Color.white && jLabel4_4.getBackground() != Color.white && jLabel4_5.getBackground() == Color.white) {
            fila = 5;
            columna = 4;
            enviarTurno(columna, fila);
        }
        else if (jLabel4_0.getBackground() != Color.white && jLabel4_1.getBackground() != Color.white && jLabel4_2.getBackground() != Color.white && jLabel4_3.getBackground() != Color.white && jLabel4_4.getBackground()  == Color.white ) {
            fila = 4;
            columna = 4;
            enviarTurno(columna, fila);
        }
        else if (jLabel4_0.getBackground() != Color.white && jLabel4_1.getBackground() != Color.white && jLabel4_2.getBackground() != Color.white && jLabel4_3.getBackground() == Color.white) {
            fila = 3;
            columna = 4;
            enviarTurno(columna, fila);
        }
        else if (jLabel4_0.getBackground() != Color.white && jLabel4_1.getBackground() != Color.white && jLabel4_2.getBackground() == Color.white) {
            fila = 2;
            columna = 4;
            enviarTurno(columna, fila);
        }
        else if (jLabel4_0.getBackground() != Color.white && jLabel4_1.getBackground() == Color.white) {
            fila = 1;
            columna = 4;
            enviarTurno(columna, fila);

        }
        else if (jLabel4_0.getBackground() == Color.white) {
            fila = 0;
            columna = 4;
            enviarTurno(columna, fila);
        }
    }

    private void jButton4ActionPerformed(ActionEvent evt) {
        if (jLabel3_0.getBackground() !=Color.white && jLabel3_1.getBackground() != Color.white && jLabel3_2.getBackground() != Color.white && jLabel3_3.getBackground() != Color.white && jLabel3_4.getBackground() != Color.white && jLabel3_5.getBackground()!= Color.white){
            jButton4.setEnabled(false);
        }
        if (jLabel3_0.getBackground() != Color.white && jLabel3_1.getBackground() != Color.white && jLabel3_2.getBackground() != Color.white && jLabel3_3.getBackground() != Color.white && jLabel3_4.getBackground() != Color.white && jLabel3_5.getBackground() == Color.white) {
            fila = 5;
            columna = 3;
            enviarTurno(columna, fila);
        }
        else if (jLabel3_0.getBackground() != Color.white && jLabel3_1.getBackground() != Color.white && jLabel3_2.getBackground() != Color.white && jLabel3_3.getBackground() != Color.white && jLabel3_4.getBackground()  == Color.white ) {
            fila = 4;
            columna = 3;
            enviarTurno(columna, fila);
        }
        else if (jLabel3_0.getBackground() != Color.white && jLabel3_1.getBackground() != Color.white && jLabel3_2.getBackground() != Color.white && jLabel3_3.getBackground() == Color.white) {
            fila = 3;
            columna = 3;
            enviarTurno(columna, fila);
        }
        else if (jLabel3_0.getBackground() != Color.white && jLabel3_1.getBackground() != Color.white && jLabel3_2.getBackground() == Color.white) {
            fila = 2;
            columna = 3;
            enviarTurno(columna, fila);
        }
        else if (jLabel3_0.getBackground() != Color.white && jLabel3_1.getBackground() == Color.white) {
            fila = 1;
            columna = 3;
            enviarTurno(columna, fila);

        }
        else if (jLabel3_0.getBackground() == Color.white) {
            fila = 0;
            columna = 3;
            enviarTurno(columna, fila);
        }
    }

    private void jButton3ActionPerformed(ActionEvent evt) {
        if (jLabel2_0.getBackground() !=Color.white && jLabel2_1.getBackground() != Color.white && jLabel2_2.getBackground() != Color.white && jLabel2_3.getBackground() != Color.white && jLabel2_4.getBackground() != Color.white && jLabel2_5.getBackground()!= Color.white){
            jButton3.setEnabled(false);
        }
        if (jLabel2_0.getBackground() != Color.white && jLabel2_1.getBackground() != Color.white && jLabel2_2.getBackground() != Color.white && jLabel2_3.getBackground() != Color.white && jLabel2_4.getBackground() != Color.white && jLabel2_5.getBackground() == Color.white) {
            fila = 5;
            columna = 2;
            enviarTurno(columna, fila);
        }
        else if (jLabel2_0.getBackground() != Color.white && jLabel2_1.getBackground() != Color.white && jLabel2_2.getBackground() != Color.white && jLabel2_3.getBackground() != Color.white && jLabel2_4.getBackground()  == Color.white ) {
            fila = 4;
            columna = 2;
            enviarTurno(columna, fila);
        }
        else if (jLabel2_0.getBackground() != Color.white && jLabel2_1.getBackground() != Color.white && jLabel2_2.getBackground() != Color.white && jLabel2_3.getBackground() == Color.white) {
            fila = 3;
            columna = 2;
            enviarTurno(columna, fila);
        }
        else if (jLabel2_0.getBackground() != Color.white && jLabel2_1.getBackground() != Color.white && jLabel2_2.getBackground() == Color.white) {
            fila = 2;
            columna = 2;
            enviarTurno(columna, fila);
        }
        else if (jLabel2_0.getBackground() != Color.white && jLabel2_1.getBackground() == Color.white) {
            fila = 1;
            columna = 2;
            enviarTurno(columna, fila);

        }
        else if (jLabel2_0.getBackground() == Color.white) {
            fila = 0;
            columna = 2;
            enviarTurno(columna, fila);
        }

    }


    private void jButton1ActionPerformed(ActionEvent evt) {
        if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() != Color.white && jLabel0_2.getBackground() != Color.white && jLabel0_3.getBackground() != Color.white && jLabel0_4.getBackground() != Color.white && jLabel0_5.getBackground() != Color.white) {
            jButton1.setEnabled(false);
        }
         if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() != Color.white && jLabel0_2.getBackground() != Color.white && jLabel0_3.getBackground() != Color.white && jLabel0_4.getBackground() != Color.white && jLabel0_5.getBackground() == Color.white) {
            fila = 5;
             columna = 0;
             enviarTurno(columna, fila);
        }
        else if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() != Color.white && jLabel0_2.getBackground() != Color.white && jLabel0_3.getBackground() != Color.white && jLabel0_4.getBackground()  == Color.white ) {
            fila = 4;
             columna = 0;
             enviarTurno(columna, fila);
        }
        else if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() != Color.white && jLabel0_2.getBackground() != Color.white && jLabel0_3.getBackground() == Color.white) {
            fila = 3;
             columna = 0;
             enviarTurno(columna, fila);
        }
        else if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() != Color.white && jLabel0_2.getBackground() == Color.white) {
            fila = 2;
             columna = 0;
             enviarTurno(columna, fila);
        }
       else if (jLabel0_0.getBackground() != Color.white && jLabel0_1.getBackground() == Color.white) {
            fila = 1;
             columna = 0;
             enviarTurno(columna, fila);

        }
        else if (jLabel0_0.getBackground() == Color.white) {
            fila = 0;
             columna = 0;
             enviarTurno(columna, fila);
        }
    }
    private void jButton2ActionPerformed(ActionEvent evt) {
        if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() != Color.white && jLabel1_2.getBackground() != Color.white && jLabel1_3.getBackground() != Color.white && jLabel1_4.getBackground() != Color.white && jLabel1_5.getBackground() != Color.white) {
            jButton2.setEnabled(false);
        }
        if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() != Color.white && jLabel1_2.getBackground() != Color.white && jLabel1_3.getBackground() != Color.white && jLabel1_4.getBackground() != Color.white && jLabel1_5.getBackground() == Color.white) {
            fila = 5;
            columna = 1;
            enviarTurno(columna, fila);
        }
        else if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() != Color.white && jLabel1_2.getBackground() != Color.white && jLabel1_3.getBackground() != Color.white && jLabel1_4.getBackground() == Color.white) {
            fila = 4;
            columna = 1;
            enviarTurno(columna, fila);
        }
        else if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() != Color.white && jLabel1_2.getBackground() != Color.white && jLabel1_3.getBackground() == Color.white) {
            fila = 3;
            columna = 1;
            enviarTurno(columna, fila);
        }
        else if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() != Color.white && jLabel1_2.getBackground() == Color.white) {
            fila = 2;
            columna = 1;
            enviarTurno(columna, fila);
        }
        else if (jLabel1_0.getBackground() != Color.white && jLabel1_1.getBackground() == Color.white) {
            fila = 1;
            columna = 1;
            enviarTurno(columna, fila);
        }
        else if (jLabel1_0.getBackground() == Color.white) {
            fila = 0;
            columna = 1;
            enviarTurno(columna, fila);
        }

    }


    public JLabel[][] getLabels() {
        return tablero;
    }

    public void enviarTurno(int x, int y) {
        cliente.enviarTurno(x, y);
    }
    public JButton[] getBotones(){
        return botones;
    }

    public JLabel getLabelC() {
        return jLabel44;
    }

    public JLabel getLabelG() {
        return jLabel37;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteF().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel0_0;
    private javax.swing.JLabel jLabel0_1;
    private javax.swing.JLabel jLabel0_2;
    private javax.swing.JLabel jLabel0_3;
    private javax.swing.JLabel jLabel0_4;
    private javax.swing.JLabel jLabel0_5;
    private javax.swing.JLabel jLabel1_0;
    private javax.swing.JLabel jLabel1_1;
    private javax.swing.JLabel jLabel1_2;
    private javax.swing.JLabel jLabel1_3;
    private javax.swing.JLabel jLabel1_4;
    private javax.swing.JLabel jLabel1_5;
    private javax.swing.JLabel jLabel2_0;
    private javax.swing.JLabel jLabel2_1;
    private javax.swing.JLabel jLabel2_2;
    private javax.swing.JLabel jLabel2_3;
    private javax.swing.JLabel jLabel2_4;
    private javax.swing.JLabel jLabel2_5;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel3_0;
    private javax.swing.JLabel jLabel3_1;
    private javax.swing.JLabel jLabel3_2;
    private javax.swing.JLabel jLabel3_3;
    private javax.swing.JLabel jLabel3_4;
    private javax.swing.JLabel jLabel3_5;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel4_0;
    private javax.swing.JLabel jLabel4_1;
    private javax.swing.JLabel jLabel4_2;
    private javax.swing.JLabel jLabel4_3;
    private javax.swing.JLabel jLabel4_4;
    private javax.swing.JLabel jLabel4_5;
    private javax.swing.JLabel jLabel5_0;
    private javax.swing.JLabel jLabel5_1;
    private javax.swing.JLabel jLabel5_2;
    private javax.swing.JLabel jLabel5_3;
    private javax.swing.JLabel jLabel5_4;
    private javax.swing.JLabel jLabel5_5;
    private javax.swing.JLabel jLabel6_0;
    private javax.swing.JLabel jLabel6_1;
    private javax.swing.JLabel jLabel6_2;
    private javax.swing.JLabel jLabel6_3;
    private javax.swing.JLabel jLabel6_4;
    private javax.swing.JLabel jLabel6_5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
